flask_app/company_blog/users/forms.py
# flask_wtfでフォーム構築、wtformsでフォームのフィールドを一括管理
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, ValidationError
# wtforms.validatorsでバリテーションチェック
from wtforms.validators import DataRequired, Email, EqualTo

from company_blog.models import User

#ログインフォーム
class LoginForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email(message="正しいメールアドレスを入力してください")])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('ログイン')


# 登録フォーム
class RegistrationForm(FlaskForm):
    # フォームに表示する入力項目の設定
    email = StringField('メールアドレス',validators=[DataRequired(), Email(message='正しいメールアドレスを入力してください')])
    username = StringField('ユーザーネーム', validators=[DataRequired()])
    password = PasswordField('パスワード', validators=[DataRequired(), EqualTo('password_confirm', message='パスワードが一致していません')])
    password_confirm = PasswordField('パスワード(確認用)', validators=[DataRequired()])
    submit = SubmitField('登録する')

    def validate_username(self, field):
        if User.query.filter_by(username=field.data).first():
            raise ValidationError('入力されたユーザー名は既に使われています。')
        
    def validate_email(self, field):
        if User.query.filter_by(email=field.data).first():
            raise ValidationError('入力されたメールアドレスは既に登録されています。')


# ユーザー更新
class UpdateUserForm(FlaskForm):
    email = StringField('メールアドレス', validators=[DataRequired(), Email(message="正しいメールアドレスを入力してください。")])
    username = StringField('ユーザー名', validators=[DataRequired()])
    password = PasswordField('パスワード', validators=[EqualTo('password_confirm', message='パスワードが一致していません')])
    password_confirm = PasswordField('パスワード(確認用)')
    submit = SubmitField('データ更新')

    def __init__(self, user_id, *args, **kwargs):
        super(UpdateUserForm, self).__init__(*args,  **kwargs)
        self.id = user_id

    # メールアドレスエラー
    def validate_email(self, field):
        if User.query.filter(User.id != self.id).filter_by(email=field.data).first():
            raise ValidationError('入力されたメールアドレスは登録されています。')
        
    # ユーザーネームエラー
    def validate_username(self, field):
        if User.query.filter(User.id != self.id).filter_by(username=field.data).first():
            raise ValidationError('入力されたユーザー名は既に使われています。')

flask_app/company_blog/users/views.py
from flask import Flask, render_template, url_for, redirect, flash, request, abort

# ログイン
from flask_login import login_user, logout_user, login_required, current_user

# 別ファイルからの読み込み
from company_blog import db
from company_blog.models import User, BlogPost, BlogCategory
from company_blog.users.forms import RegistrationForm, LoginForm, UpdateUserForm
from flask import Blueprint
from company_blog.main.forms import BlogSearchForm

users = Blueprint('users', __name__)

# ログインページ
@users.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    # 入力された内容に問題がないかを見る
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user is not None:
            if user.check_password(form.password.data):
                login_user(user)
                next = request.args.get('next')
                if next == None  or not next[0] ==  '/':
                    next = url_for('main.blog_maintenance')
                return redirect(next)

            else:
                flash('パスワードが一致しません')
        else:
            flash('入力されたユーザーは存在しません')

    return render_template('users/login.html', form=form)

# ログアウト
@users.route('/logput')
def logout():
    logout_user()
    return redirect(url_for('users.login'))

#View関数
@users.route('/register', methods=['GET', 'POST'])
@login_required
def register():
    # フォームを使えるようにインスタンス化
    form = RegistrationForm()
    if not current_user.is_administrator():
        abort(403)
    # 入力したデータをチェックする
    if form.validate_on_submit():

        # セッションにデータ格納
        # session['email'] = form.email.data
        # session['username'] = form.username.data
        # session['password'] = form.password.data

        #フォームのデータをDBに格納する
        user = User(email=form.email.data, username=form.username.data, password=form.password.data, administrator="0")
        db.session.add(user)
        db.session.commit()

        # 登録後に表示するメッセージ
        flash('ユーザーが登録されました')
        return redirect(url_for('users.user_maintenance'))
    return render_template('users/register.html', form=form)

# ユーザー管理ページ
@users.route('/user_maintenance')
@login_required
def user_maintenance():
    page = request.args.get('page', 1 ,type=int)
    # usersテーブルからデータを全件取得
    users = User.query.order_by(User.id).paginate(page=page, per_page=10)
    return render_template('users/user_maintenance.html', users=users)

# ユーザー更新ページ
@users.route('/<int:user_id>/account', methods=['GET', 'POST'])
@login_required
def account(user_id):
    user = User.query.get_or_404(user_id)
    if user.id != current_user.id and not current_user.is_administrator():
        abort(403)
    form = UpdateUserForm(user_id)
    # 初期表示後の処理
    if form.validate_on_submit():
        user.username = form.username.data
        user.email = form.email.data
        
        if form.password.data:
            user.password = form.password.data
            
        db.session.commit()
        flash('ユーザーアカウントが更新されました。')

        return redirect(url_for('users.user_maintenance'))
    # 初期表示
    elif request.method == 'GET':
        form.username.data = user.username
        form.email.data = user.email
    
    return render_template('users/account.html', form=form)

# ユーザーデータ削除
@users.route('/<int:user_id>/delete', methods=['GET', 'POST'])
@login_required
def delete_user(user_id):
    user = User.query.get_or_404(user_id)
    # 管理者権限
    if not current_user.is_administrator():
        abort(403)
    if user.is_administrator():
        flash('管理者は削除できません')
        return redirect(url_for('users.account', user_id=user_id))
    db.session.delete(user)
    db.session.commit()
    flash(f'ユーザーのアカウントが削除されました。')
    return redirect(url_for('users.user_maintenance'))

# ユーザー投稿数
@users.route('/<int:user_id>/user_posts')
@login_required
def user_posts(user_id):
    form = BlogSearchForm()
    # ユーザーの取得
    user = User.query.filter_by(id=user_id).first_or_404()

    # ブログ記事の取得
    page = request.args.get('page', 1, type=int)
    blog_posts = BlogPost.query.filter_by(user_id=user_id).order_by(BlogPost.id.desc()).paginate(page=page, per_page=10)

    # 最新記事の取得
    recent_blog_posts = BlogPost.query.order_by(BlogPost.id.desc()).limit(5).all()

    # カテゴリーの取得
    blog_categories = BlogCategory.query.order_by(BlogCategory.id.asc()).all()

    return render_template('index.html', blog_posts=blog_posts, recent_blog_posts=recent_blog_posts, blog_categories=blog_categories, user=user,form=form)

flask_app/company_blog/templates/users/account.html
{% extends 'base.html' %}

{% block content %}

    <!-- コンテンツ -->
    <div class="container" style="margin-top:4rem;">
      <div class="col-md-12 mx-auto my-5">

          <!-- フォーム -->
          <div class="row">
            <div class="col-md-6 mx-auto mt-2">
              <h2 class="text-center mb-3">ユーザー更新</h2>
              <p class="text-center">ユーザー情報に変更がある場合は更新してください</p>
              <form method="POST">
                {{ form.hidden_tag() }}
                <div class="mb-3">
                  {{ form.username.label }}<br>
                  {{ render_field(form.username, class="form-control border border-info") }}
                </div>
                <div class="mb-3">
                  {{ form.email.label }}<br>
                  {{ render_field(form.email, class="form-control border border-success") }}
                </div>
                <div class="mb-3">
                  {{ form.password.label }}<br>
                  {{ render_field(form.password, class="form-control border border-success") }}
                </div>
                <div class="mb-3">
                  {{ form.password_confirm.label }}<br>
                  {{ render_field(form.password_confirm, class="form-control border border-success") }}
                </div>
                <div class="text-center">
                    {{ form.submit(class="btn btn-primary mx-auto w-25 mb-4") }}
                  <!-- Button trigger modal -->
                   {% if current_user.is_administrator() %}
                  <button type="button" class="btn btn-danger ml-4 mx-auto" style="display: block;" data-bs-toggle="modal" data-bs-target="#user_delete">
                    ユーザー情報を削除する
                  </button>
                  {% endif %}

                </div>
              </form>
              
              <!-- Modal -->
              <div class="modal fade" id="user_delete" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title" id="exampleModalLabel">ユーザー情報の削除</h5>
                      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                      このユーザーの情報を削除しますか？
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Close</button>
                      <form action="{{url_for('users.delete_user', user_id=form.id)}}" method="POST">
                        <button type="submit" class="btn btn-danger">削除する</button>
                      </form>
                    </div>
                  </div>
                </div>
              </div>
          </div>
         </div>
      </div>
    </div>
{% endblock content %}

flask_app/company_blog/templates/users/login.html
{% extends 'base.html' %}

{% block content %}

    <!-- コンテンツ -->
    <div class="container" style="margin-top:4rem;">
      <div class="col-md-12 mx-auto my-5">

          <!-- フォーム -->
          <div class="row">
            <div class="col-md-6 mx-auto mt-2">
              <h2 class="text-center mb-3">ログイン画面</h2>
              <form method="POST">
                {{ form.hidden_tag() }}
                <div class="mb-3">
                  {{ form.email.label }}<br>
                  {{ render_field(form.email, class="form-control border border-success") }}
                
                </div>
                <div class="mb-3">
                  {{ form.password.label }}<br>
                  {{ render_field(form.password, class="form-control border border-success") }}
                </div>
                <div class="mt-6 text-center">
                  {{ form.submit(class="btn btn-primary mx-auto w-25") }}
                </div>
              </form>
          </div>
         </div>
      </div>
    </div>
{% endblock content %}

flask_app/company_blog/templates/users/register.html
{% extends 'base.html' %}

{% block content %}
    <!-- コンテンツ -->
    <div class="container" style="margin-top:4rem;">
      <div class="col-md-12 mx-auto my-5">

          <!-- フォーム -->
          <div class="row">
            <div class="col-md-6 mx-auto mt-2">
              <h2 class="text-center mb-3">ユーザー登録</h2>
              <p class="text-center">ユーザー情報を登録してください</p>
              <form method="POST">
                {{ form.hidden_tag() }}
                <!-- form.(フィールド名)で入力項目を呼び出す -->
                <div class="mb-3">
                  {{ form.username.label }}<br>
                  {{ render_field(form.username, class="form-control border border-success") }}
                </div>
                <div class="mb-3">
                  {{ form.email.label }}<br>
                  {{ render_field(form.email, class="form-control border border-success") }}
                </div>
                <div class="mb-3">
                  {{ form.password.label }}<br>
                  {{ render_field(form.password, class="form-control border border-success") }}
                </div>
                <div class="mb-3">
                  {{ form.password_confirm.label }}<br>
                  {{ render_field(form.password_confirm, class="form-control border border-success") }}
                </div>
                <div class="mt-6 text-center">
                  {{ form.submit(class="btn btn-primary mx-auto w-25") }}
                </div>
              </form>
          </div>
         </div>
      </div>
    </div>
{% endblock content %}

flask_app/company_blog/templates/users/user_maintenance.html
{% extends 'base.html' %}

{% block content %}
    <!-- コンテンツ -->
    <div class="container" style="margin-top:4rem;">
      <div class="col-md-12 mx-auto my-5">
        <h2 class="text-primary text-center py-3">ユーザー管理画面</h2>

        {% if current_user.is_administrator() %}
        <div class="text-center pt-2 pb-4">
          <a href="{{url_for('users.register')}}" class="btn btn-primary">新規ユーザー登録</a>
        </div>
        {% endif %}

        <section class="col-md-10 mx-auto">
          <table class="table">
            <thead>
              <tr class="bg-dark text-white">
                <th scope="col">ID</th>
                <th scope="col">ユーザー名</th>
                <th scope="col">メールアドレス</th>
                <th scope="col">管理者</th>
                <th scope="col">ブログ投稿数</th>
                <th scope="col">登録情報変更</th>
              </tr>
            </thead>
            <tbody>
              {% for user in users.items %}
              <tr>
                <th scope="row">{{ user.id }}</th>
                <td class="col-md-2">{{ user.username }}</td>
                <td class="col-md-3">{{ user.email }}</td>
                <td class="col-md-2">{{user.administrator}}</td>
                <td class="col-md-2"><a href="{{ url_for('users.user_posts', user_id=user.id) }}">{{ user.count_posts(user.id) }}</a></td>
                {% if current_user.is_administrator() or current_user.id == user.id %}
                <td class="col-md-2">
                  <a href="{{url_for('users.account', user_id=user.id)}}" class="btn btn-success">
                    変更〇
                  </a>
                </td>
                {% else %}
                <td class="col-md-2">
                  <a href="#" class="btn btn-success">
                    変更×
                  </a>
                </td>
                {% endif %}
              </tr>
              {% endfor %}
            </tbody>
          </table>
          <!-- ページャー -->
          <nav aria-label="Page navigation example">
            <ul class="pagination">
              <li {% if users.has_prev %} class="page-item" {% else %} class="page-item disabled" {% endif %}>
                <a class="page-link" href=" {% if users.has_prev %} {{url_for('users.user_maintenance', page=users.prev_num)}} {% else %} # {% endif %}" aria-label="Previous">
                  <span aria-hidden="true">&laquo;</span>
                </a>
              </li>

              {% for page_num in users.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
                {% if page_num %}
                  {% if users.page == page_num %}
                    <li class="page-item disabled"><a class="page-link" href="#">{{page_num}}</a></li>
                  {% else %}
                    <li class="page-item"><a class="page-link" href="{{url_for('users.user_maintenance', page=page_num)}}">{{page_num}}</a></li>
                  {% endif %}
                {% else %}
                  <li class="page-item disabled"><a class="page-link" href="#">&hellip;</a></li>
                {% endif %}
              {% endfor %}

              <li {% if users.has_next %} class="page-item" {% else %} class="page-item disabled" {% endif %}>
                <a class="page-link" href=" {% if users.has_next %} {{url_for('users.user_maintenance', page=users.next_num)}} {% else %} # {% endif %}" aria-label="Next">
                  <span aria-hidden="true">&raquo;</span>
                </a>
              </li>
            </ul>
          </nav>
        <section>
      </div>
    </div>
{% endblock content %}