flask_app/company_blog/main/views.py
from flask import Blueprint, render_template ,request, url_for, redirect, flash, abort
from flask_login import login_required, current_user
from company_blog.models import BlogCategory, BlogPost, Inquiry
from company_blog.main.forms import BlogCategoryForm, UpdateCategoryForm, BlogPostForm, BlogSearchForm, InquiryForm
from company_blog import db
from company_blog.main.image_handler import add_featured_image

main = Blueprint('main', __name__)

# TOPページ
@main.route('/')
def index():
    form = BlogSearchForm()
    # ブログ記事の取得
    page = request.args.get('page', 1, type=int)
    blog_posts = BlogPost.query.order_by(BlogPost.id.desc()).paginate(page=page, per_page=10)

    # 最新記事の取得
    recent_blog_posts = BlogPost.query.order_by(BlogPost.id.desc()).limit(5).all()

    # カテゴリーの取得
    blog_categories = BlogCategory.query.order_by(BlogCategory.id.asc()).all()

    return render_template('index.html', blog_posts=blog_posts, recent_blog_posts=recent_blog_posts, blog_categories=blog_categories, form=form)


# カテゴリー一覧
@main.route('/category_maintenance', methods=['GET', 'POST'])
@login_required
def category_maintenance():
    # データの読み込み
    page = request.args.get('page', 1, type=int)
    blog_categories = BlogCategory.query.order_by(BlogCategory.id.asc()).paginate(page=page, per_page=10)
    form = BlogCategoryForm()

    if form.validate_on_submit():
        blog_category = BlogCategory(category=form.category.data)
        db.session.add(blog_category)
        db.session.commit()
        flash('ブログカテゴリーが追加されました')
        return redirect(url_for('main.category_maintenance'))
    elif form.errors:
        form.category.data = ''
        flash(form.errors['category'][0])
    return render_template('category_maintenance.html', blog_categories=blog_categories, form=form)

# カテゴリー更新
@main.route('/<int:blog_category_id>/blog_category', methods=['GET', 'POST'])
@login_required
def blog_category(blog_category_id):
    # 管理者でないとき
    if not current_user.is_administrator():
        abort(403)
    blog_category = BlogCategory.query.get_or_404(blog_category_id)
    form = UpdateCategoryForm(blog_category_id)

    # 間違ったときの処理
    if form.validate_on_submit():
        blog_category.category = form.category.data
        db.session.commit()
        flash('ブログカテゴリーが更新されました。')
        return redirect(url_for('main.category_maintenance'))

    elif request.method == 'GET':
        form.category.data = blog_category.category
    return render_template('blog_category.html', form=form)

# カテゴリー削除
@main.route('/<int:blog_category_id>/delete_category', methods=['GET', 'POST'])
@login_required
def delete_category(blog_category_id):
    # 管理者でないとき
    if not current_user.is_administrator():
        abort(403)

    # カテゴリーの削除処理
    blog_category = BlogCategory.query.get_or_404(blog_category_id)
    db.session.delete(blog_category)
    db.session.commit()
    flash('ブログカテゴリーが削除されました')
    return redirect(url_for('main.category_maintenance'))

# ブログ投稿
@main.route('/create_post', methods=['GET', 'POST'])
@login_required
def create_post():
    form = BlogPostForm()
    if form.validate_on_submit():
        if form.picture.data:
            pic = add_featured_image(form.picture.data)
        else:
            pic = ''
        blog_post = BlogPost(title=form.title.data, text=form.text.data, summary=form.summary.data, featured_image=pic,  user_id=current_user.id, category_id=form.category.data)
        db.session.add(blog_post)
        db.session.commit()
        flash('ブログが投稿されました。')
        return redirect(url_for('main.blog_maintenance'))
    return render_template('create_post.html', form=form)

# ブログ管理ページ
@main.route('/blog_maintenance')
@login_required
def blog_maintenance():
    page = request.args.get('page', 1, type=int)
    blog_posts = BlogPost.query.order_by(BlogPost.id.desc()).paginate(page=page, per_page=10)
    return render_template('blog_maintenance.html', blog_posts=blog_posts)

# ブログ詳細
@main.route('/<int:blog_post_id>/blog_post')
def blog_post(blog_post_id):
    form = BlogSearchForm()

    # 最新記事の取得
    recent_blog_posts = BlogPost.query.order_by(BlogPost.id.desc()).limit(5).all()

    # カテゴリーの取得
    blog_categories = BlogCategory.query.order_by(BlogCategory.id.asc()).all()

    # 検索ページの処理
    blog_post = BlogPost.query.get_or_404(blog_post_id)
    return render_template('blog_post.html', post=blog_post, recent_blog_posts=recent_blog_posts, blog_categories=blog_categories, form=form)

# ブログの削除機能
@main.route('/<int:blog_post_id>/blog_delete', methods=['GET', 'POST'])
@login_required
def blog_delete(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)
    if blog_post.author != current_user:
        abort(403)
    db.session.delete(blog_post)
    db.session.commit()
    return redirect(url_for('main.blog_maintenance'))

# ブログ更新
@main.route('/<int:blog_post_id>/update_blog', methods=['GET', 'POST'])
@login_required
def update_blog(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)
    if blog_post.author != current_user:
        abort(403)
    form = BlogPostForm()
    if form.validate_on_submit():
        blog_post.title = form.title.data
        if form.picture.data:
            blog_post.featured_image = add_featured_image(form.picture.data)
        blog_post.text = form.text.data
        blog_post.summary = form.summary.data
        blog_post.category_id = form.category.data
        db.session.commit()
        flash('ブログ投稿が更新されました')
        return redirect(url_for('main.blog_post', blog_post_id=blog_post.id))
    elif request.method == 'GET':
        form.title.data = blog_post.title
        form.picture.data = blog_post.featured_image
        form.text.data = blog_post.text
        form.summary.data = blog_post.summary
        form.category.data = blog_post.category_id
    return render_template('create_post.html', form=form)

# ブログ記事検索
@main.route('/search', methods=['GET', 'POST'])
def search():
    form = BlogSearchForm()
    search_text = ""

    # 検索キーワードが送信されたときの処理
    if form.validate_on_submit():
        search_text = form.searchtext.data
    elif request.method == 'GET':
        form.searchtext.data = ""

    # ブログ記事の取得
    page = request.args.get('page', 1, type=int)
    blog_posts = BlogPost.query.filter((BlogPost.text.contains(search_text)) | (BlogPost.title.contains(search_text)) | (BlogPost.summary.contains(search_text))).paginate(page=page, per_page=10)

    # 最新記事の取得
    recent_blog_post = BlogPost.query.order_by(BlogPost.id.desc()).limit(5).all()

    # カテゴリーの取得
    blog_categories = BlogCategory.query.order_by(BlogCategory.id.asc()).all()

    return render_template('index.html', blog_posts=blog_posts, recent_blog_post=recent_blog_post, blog_categories=blog_categories, form=form, search_text=search_text)

# カテゴリー別の機能
@main.route('/<int:id>/category_posts', methods=['GET', 'POST'])
def category_posts(id):
    form = BlogSearchForm()

    # カテゴリー名の取得
    blog_category = BlogCategory.query.filter_by(id=id).first_or_404()

    # ブログ記事の取得
    page = request.args.get('page', 1, type=int)
    blog_posts = BlogPost.query.filter_by(id=id).order_by(BlogPost.id.desc()).paginate(page=page, per_page=10)

    # 最新記事の取得
    recent_blog_post = BlogPost.query.order_by(BlogPost.id.desc()).limit(5).all()

    # カテゴリーの取得
    blog_categories = BlogCategory.query.order_by(BlogCategory.id.asc()).all()

    return render_template('index.html', blog_posts=blog_posts, recent_blog_post=recent_blog_post, blog_categories=blog_categories, id=id, form=form)

# お問い合わせフォーム
@main.route('/inquiry', methods=['GET', 'POST'])
def inquiry():
    form = InquiryForm()

    if form.validate_on_submit():
        inquiry = Inquiry(name=form.name.data, email=form.email.data, title=form.title.data, text=form.text.data)
        db.session.add(inquiry)
        db.session.commit()
        flash('お問い合わせが送信されました')
        return redirect(url_for('main.inquiry'))
    return render_template('inquiry.html', form = form)

# お問い合わせ管理画面
@main.route('/inquiry_maintenance', methods=['GET', 'POST'])
@login_required
def inquiry_maintenance():
    page = request.args.get('page', 1, type=int)
    inquiries = Inquiry.query.order_by(Inquiry.id.desc()).paginate(page=page, per_page=10)
    return render_template('inquiry_maintenance.html', inquiries=inquiries)

# お問い合わせ詳細画面
@main.route('/<int:inquiry_id>/display_inquiry')
@login_required
def display_inquiry(inquiry_id):
    inquiry = Inquiry.query.get_or_404(inquiry_id)
    form = InquiryForm()
    form.name.data = inquiry.name
    form.email.data = inquiry.email
    form.title.data = inquiry.title
    form.text.data = inquiry.text
    return render_template('inquiry.html', form=form, inquiry_id=inquiry_id)

# お問い合わせデータ削除
@main.route('/<int:inquiry_id>/delete_inquiry', methods=['GET', 'POST'])
@login_required
def delete_inquiry(inquiry_id):
    inquiries = Inquiry.query.get_or_404(inquiry_id)
    if not current_user.is_administrator():
        abort(403)
    db.session.delete(inquiries)
    db.session.commit()
    flash('お問い合わせが削除されました')
    return redirect(url_for('main.inquiry_maintenance'))

# 会社概要ページ
@main.route('/info')
def info():
    return render_template('info.html')

flask_app/company_blog/users/views.py
from flask import Flask, render_template, url_for, redirect, flash, request, abort

# ログイン
from flask_login import login_user, logout_user, login_required, current_user

# 別ファイルからの読み込み
from company_blog import db
from company_blog.models import User, BlogPost, BlogCategory
from company_blog.users.forms import RegistrationForm, LoginForm, UpdateUserForm
from flask import Blueprint
from company_blog.main.forms import BlogSearchForm

users = Blueprint('users', __name__)

# ログインページ
@users.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    # 入力された内容に問題がないかを見る
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user is not None:
            if user.check_password(form.password.data):
                login_user(user)
                next = request.args.get('next')
                if next == None  or not next[0] ==  '/':
                    next = url_for('main.blog_maintenance')
                return redirect(next)

            else:
                flash('パスワードが一致しません')
        else:
            flash('入力されたユーザーは存在しません')

    return render_template('users/login.html', form=form)

# ログアウト
@users.route('/logput')
def logout():
    logout_user()
    return redirect(url_for('users.login'))

#View関数
@users.route('/register', methods=['GET', 'POST'])
@login_required
def register():
    # フォームを使えるようにインスタンス化
    form = RegistrationForm()
    if not current_user.is_administrator():
        abort(403)
    # 入力したデータをチェックする
    if form.validate_on_submit():

        # セッションにデータ格納
        # session['email'] = form.email.data
        # session['username'] = form.username.data
        # session['password'] = form.password.data

        #フォームのデータをDBに格納する
        user = User(email=form.email.data, username=form.username.data, password=form.password.data, administrator="0")
        db.session.add(user)
        db.session.commit()

        # 登録後に表示するメッセージ
        flash('ユーザーが登録されました')
        return redirect(url_for('users.user_maintenance'))
    return render_template('users/register.html', form=form)

# ユーザー管理ページ
@users.route('/user_maintenance')
@login_required
def user_maintenance():
    page = request.args.get('page', 1 ,type=int)
    # usersテーブルからデータを全件取得
    users = User.query.order_by(User.id).paginate(page=page, per_page=10)
    return render_template('users/user_maintenance.html', users=users)

# ユーザー更新ページ
@users.route('/<int:user_id>/account', methods=['GET', 'POST'])
@login_required
def account(user_id):
    user = User.query.get_or_404(user_id)
    if user.id != current_user.id and not current_user.is_administrator():
        abort(403)
    form = UpdateUserForm(user_id)
    # 初期表示後の処理
    if form.validate_on_submit():
        user.username = form.username.data
        user.email = form.email.data
        
        if form.password.data:
            user.password = form.password.data
            
        db.session.commit()
        flash('ユーザーアカウントが更新されました。')

        return redirect(url_for('users.user_maintenance'))
    # 初期表示
    elif request.method == 'GET':
        form.username.data = user.username
        form.email.data = user.email
    
    return render_template('users/account.html', form=form)

# ユーザーデータ削除
@users.route('/<int:user_id>/delete', methods=['GET', 'POST'])
@login_required
def delete_user(user_id):
    user = User.query.get_or_404(user_id)
    # 管理者権限
    if not current_user.is_administrator():
        abort(403)
    if user.is_administrator():
        flash('管理者は削除できません')
        return redirect(url_for('users.account', user_id=user_id))
    db.session.delete(user)
    db.session.commit()
    flash(f'ユーザーのアカウントが削除されました。')
    return redirect(url_for('users.user_maintenance'))

# ユーザー投稿数
@users.route('/<int:user_id>/user_posts')
@login_required
def user_posts(user_id):
    form = BlogSearchForm()
    # ユーザーの取得
    user = User.query.filter_by(id=user_id).first_or_404()

    # ブログ記事の取得
    page = request.args.get('page', 1, type=int)
    blog_posts = BlogPost.query.filter_by(user_id=user_id).order_by(BlogPost.id.desc()).paginate(page=page, per_page=10)

    # 最新記事の取得
    recent_blog_posts = BlogPost.query.order_by(BlogPost.id.desc()).limit(5).all()

    # カテゴリーの取得
    blog_categories = BlogCategory.query.order_by(BlogCategory.id.asc()).all()

    return render_template('index.html', blog_posts=blog_posts, recent_blog_posts=recent_blog_posts, blog_categories=blog_categories, user=user,form=form)

flask_app/company_blog/templates/_formhelpers.html
{% macro render_field(field) %}
{{ field(**kwargs)|safe }}
{% if field.errors %}
    {% for error in field.errors %}
    <p class="text-danger font-bold">{{ error }}</p>
    {% endfor %}
{% endif %}
{% endmacro %}

flask_app/company_blog/templates/base.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- cd editor -->
    <script src="https://cdn.ckeditor.com/4.22.1/standard/ckeditor.js"></script>
    <!-- bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <!-- bootstrap-js -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <title>Hoshitetsu Company</title>
</head>
<body>
    <header class="bg-dark fixed-top">
      <nav class="navbar navbar-expand-lg navbar-light col-md-10 mx-auto">
        <div class="container">
          <a class="navbar-brand text-white" href="{{ url_for('main.index') }}">Hoshitetsu.Inc</a>
          <button class="navbar-toggler bg-white" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link text-white" href="{{url_for('main.index')}}">ホーム</a>
              </li>
              <li class="nav-item">
                <a class="nav-link text-white" href="{{ url_for('main.info') }}">会社情報</a>
              </li>
              <li class="nav-item">
                <a class="nav-link text-white" href="{{url_for('main.inquiry')}}">お問い合わせ</a>
              </li>
            </ul>
          </div>
          <ul class="navbar-nav d-md-none d-lg-flex">
            <li class="nav-item">
              <a class="nav-link text-white"href="{{url_for('main.blog_maintenance')}}">ブログ</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-white" href="{{url_for('main.category_maintenance')}}">カテゴリ</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-white" href="{{url_for('main.inquiry_maintenance')}}">お問い合わせ</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-white" href="{{url_for('users.user_maintenance')}}">ユーザー</a>
            </li>
            {% if current_user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link text-white" href="{{url_for('users.logout')}}">ログアウト</a>
            </li>
            <li class="nav-item">
              <div class="nav-link text-white" href="#" tabindex="-1" aria-disabled="true">{{ current_user.username }}</div>
            </li>
            {% endif %}
          </ul>
        </div>
      </nav>

    </header>

    {% from "_formhelpers.html" import render_field %}

    <!-- コンテンツ -->
    <div class="container" style="margin-top:4rem;">
      <div class="col-md-12 mx-auto my-5">
        <!-- アラート -->
         {% for message in get_flashed_messages() %}
        <div class="alert alert-warning m-2" role="alert">
          {{ message }}
        </div>
        {% endfor %}
        {% block content %}
        {% endblock content %}
      </div>
    </div>

    <!-- フッター -->
    <footer id="footer" class="footer bg-dark fixed-bottom">
      <div class="text-white py-3 text-center">copyright 2023 ©Hoshitetsu</div>
    </footer>
</body>
</html>

flask_app/company_blog/templates/blog_category.html
{% extends 'base.html' %}

{% block content %}
    <!-- コンテンツ -->
    <div class="container" style="margin-top:4rem;">
      <div class="col-md-12 mx-auto my-5">

          <!-- フォーム -->
          <div class="row">
            <div class="col-md-6 mx-auto mt-2">
              <h2 class="text-center mb-3">カテゴリー更新</h2>
              <p class="text-center">ブログのカテゴリーを変える場合はこちらから更新してください。</p>
              <form method="POST">
                {{ form.hidden_tag() }}
                <div class="mb-3">
                  <label for="username" class="form-label">カテゴリー名</label><br>
                  {{ render_field(form.category, class="form-control border border-info") }}
                </div>
                <div class="text-center">
                  {{ form.submit(class="btn btn-primary mb-2") }}
                  <!-- Button trigger modal -->
                  <button type="button" class="btn btn-danger ml-4 mx-auto" style="display: block;" data-bs-toggle="modal" data-bs-target="#category_update">
                    カテゴリー情報を削除する
                  </button>

                </div>
              </form>

              <!-- Modal -->
              <div class="modal fade" id="category_update" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title" id="exampleModalLabel">カテゴリー削除</h5>
                      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                      このカテゴリーを削除しますか？
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Close</button>
                      <form action="{{url_for('main.delete_category', blog_category_id=form.id)}}" method="POST">
                        <button type="submit" class="btn btn-danger">削除する</button>
                      </form>
                    </div>
                  </div>
                </div>
              </div>
          </div>
         </div>
      </div>
    </div>
{% endblock content %}

flask_app/company_blog/templates/blog_maintenance.html
{% extends 'base.html' %}

{% block content %}

    <!-- コンテンツ -->
    <div class="container" style="margin-top:4rem;">
      <div class="col-md-12 mx-auto my-5">
        <h2 class="text-primary text-center py-3">ポスト管理画面</h2>

        <div class="text-center pt-2 pb-4">
          <a href="{{ url_for('main.create_post') }}" class="btn btn-success">新規ポスト投稿</a>
        </div>
        <section class="col-md-8 mx-auto">
          <table class="table">
            <thead>
              <tr class="bg-dark text-white">
                <th scope="col">ID</th>
                <th scope="col">タイトル</th>
                <th scope="col">作成日</th>
                <th scope="col">投稿者</th>
                <th scope="col">ポスト詳細</th>
              </tr>
            </thead>
            <tbody>
              {% for post in blog_posts.items %}
              <tr >
                <th class="col-md-2">{{ post.id }}</th>
                <td class="col-md-4">{{ post.title }}</td>
                <td class="col-md-2">{{ post.date.strftime('%Y-%m-%d') }}</td>
                <td class="col-md-2">{{ post.author.username }}</td>
                <td class="col-md-2">
                  <a href="{{ url_for('main.blog_post', blog_post_id=post.id) }}" class="btn btn-success" >
                    ポスト詳細
                  </a>
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
          <!-- ページャー -->
          <nav aria-label="Page navigation example">
            <ul class="pagination">
              <li {% if blog_posts.has_prev %} class="page-item" {% else %} class="page-item disabled" {% endif %}>
                <a class="page-link" href=" {% if blog_posts.has_prev %} {{url_for('main.blog_maintenance', page=blog_posts.prev_num)}} {% else %} # {% endif %}" aria-label="Previous">
                  <span aria-hidden="true">&laquo;</span>
                </a>
              </li>

              {% for page_num in blog_posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
                {% if page_num %}
                  {% if blog_posts.page == page_num %}
                    <li class="page-item disabled"><a class="page-link" href="#">{{page_num}}</a></li>
                  {% else %}
                    <li class="page-item"><a class="page-link" href="{{url_for('main.blog_maintenance', page=page_num)}}">{{page_num}}</a></li>
                  {% endif %}
                {% else %}
                  <li class="page-item disabled"><a class="page-link" href="#">&hellip;</a></li>
                {% endif %}
              {% endfor %}

              <li {% if blog_posts.has_next %} class="page-item" {% else %} class="page-item disabled" {% endif %}>
                <a class="page-link" href=" {% if blog_posts.has_next %} {{url_for('main.blog_maintenance', page=blog_posts.next_num)}} {% else %} # {% endif %}" aria-label="Next">
                  <span aria-hidden="true">&raquo;</span>
                </a>
              </li>
            </ul>
          </nav>
        <section>
      </div>
    </div>
{% endblock %}

flask_app/company_blog/templates/blog_post.html
{% extends 'base.html' %}

{% block content %}
    <!-- コンテンツ -->
    <div class="container" style="margin-top:4rem;">
      <div class="col-md-12 mx-auto my-5">
        <section id="page-title">
            <div class="container py-3 bg-light">
                <div class="row">
                    <div class="col-md-6 m-auto text-center">
                       <h1 class="fst-italic"> {{post.title}}</h1> 
                       <hr>
                       <p>{{ post.date.strftime('%Y%m%d') }} : {{ post.author.username }}({{ post.blogcategory.category }})</p>
                    </div>
                </div>
            </div>
        </section>
        <!-- コンテンツ本体 -->
        <div class="container mt-3">
            <div class="row mb-2">
                <!-- コンテンツ -->
                 <div class="col-8">
                    <!-- ブログ投稿 -->
                     <section id="blog_post">
                        <div class="container py-2 bg-light">
                          {% if post.featured_image %}
                            <div class="mb-3" style="text-align: center;">
                                <img src="{{ url_for('static', filename='featured_image/' + post.featured_image ) }}" class="img-fluid">
                            </div>
                          {% endif %}
                            <p class="mb-3">{{ post.text|safe }}</p>
                        </div>
                     </section>

                    <!-- 記事関連のボタン -->
                    <div class="row text-center bg-light mt-3 p-3">
                        {% if current_user.is_active %}
                          {% if post.author == current_user %}
                          <div class="col-md-2">
                            <a href="{{ url_for('main.update_blog', blog_post_id=post.id) }}" class="btn btn-success" style="display: inline-block;">記事を更新</a>
                          </div>
                          <!-- 削除モーダルトリガー -->
                          <div class="col-md-2">
                            <button type="button" class="btn btn-danger" style="display: inline-block;" data-bs-toggle="modal" data-bs-target="#blog_delete">
                            記事を削除
                            </button>
                          </div>
                          {% endif %}
                        {% endif %}
                        <div class="col-md-2">
                          <button type="button" class="btn btn-secondary" style="display: inline-block;" onclick="history.back()">
                          戻る
                          </button>
                        </div>
                    </div>
                 </div>
                 <!-- サイドバー -->
                  <div class="col-md-4">
                    <div class="position-sticky" style="top: 2rem;">
                        <!-- 検索 -->
                         <div class="container-fruid mb-3">
                          <form action="{{ url_for('main.search') }}" method="POST" class="d-flex">
                              {{ form.hidden_tag() }}
                              {{ render_field(form.searchtext, class="form-control me-2", placeholder="検索するテキストを入力") }}
                              {{ form.submit(class="btn-btn-outline-success") }}
                          </form>
                         </div>

                        <!-- 会社情報 -->
                        <div class="p-4 mb-4 bg-light">
                            <h4 class="fst-italic">会社情報</h4>
                            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab tempore numquam corrupti odit aliquam eveniet dicta magni, perspiciatis accusamus esse quod fugit a, et iste fugiat quaerat nisi inventore in.</p>
                        </div>

                        <!-- 最新情報 -->
                        <div class="p-4 mb-4 bg-light">
                            <h4 class="fst-italic">RECENT POST <span class="ms-2 fs-6">最新記事</span></h4>
                            <hr>
                            <ol class="list-unstyled">
                              {% for recent_post in recent_blog_posts %}
                                <li>
                                    <a href="{{ url_for('main.blog_post', blog_post_id=post.id) }}" class="text-decoration-none text-dark">
                                        {% if recent_post.featured_image %}
                                        <img src="{{ url_for('static', filename='featured_image/' + recent_post.featured_image) }}" class="img-fluid" width="90" height="50">
                                        {% else %}
                                        <div style="width: 90px; height: 50px; background-color: #999; display: inline-block;" class="img-fluid"></div>
  
                                        {% endif %}
                                        <span class="ms-2">{{ recent_post.title }}</span>
                                    </a>
                                    <hr>
                                </li>
                              {% endfor %}
                            </ol>
                        </div>

                        <!-- カテゴリー -->
                        <div class="p-4 bg-light">
                            <h4 class="fst-italic">CATEGORY <span class="ms-2 fs-6">カテゴリー一覧</span></h4>
                            <hr>
                            <ol class="list-unstyled">
                              {% for blog_category in blog_categories %}
                                <li>
                                    <a href="{{ url_for('main.category_posts', id=blog_category.id) }}" class="text-decoration-none text-dark">
                                        <span class="ms-2">{{ blog_category.category }}</span>
                                    </a>
                                    <hr>
                                </li>
                              {% endfor %}
                            </ol>
                        </div>
                        
                    </div>
                  </div>
            </div>
        </div>

          <!-- モーダル関連 -->
            <div class="modals col-md-4 mx-auto py-3">
              <!-- Modal -->
              <div class="modal fade" id="blog_delete" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title" id="exampleModalLabel"></h5>
                      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                      このブログ記事を削除しますか？
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Close</button>
                      <form action="{{ url_for('main.blog_delete', blog_post_id=post.id) }}" method="POST">
                        <button type="submit" class="btn btn-danger">削除する</button>
                      </form>
                    </div>
                  </div>
                </div>
              </div>
          </div>
      </div>
    </div>
{% endblock content %}